# golangci-lint v2 configuration
# See: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/olekukonko/tablewriter.Table).Append
      - (*github.com/olekukonko/tablewriter.Table).Render
      - (net/http.ResponseWriter).Write
      - (*github.com/spf13/cobra.Command).MarkFlagRequired

issues:
  exclude-dirs:
    - cmd/thecloud
    - pkg/sdk
    - internal/handlers/ws
  max-issues-per-linter: 50
  max-same-issues: 10
