# golangci-lint v2 configuration

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - cmd/thecloud
      - pkg/sdk
      - internal/handlers/ws
  settings:
    errcheck:
      exclude-functions:
        # CLI output functions - stdout rarely fails
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Printf
        - fmt.Println
        # Tablewriter - output wrappers
        - (*github.com/olekukonko/tablewriter.Table).Append
        - (*github.com/olekukonko/tablewriter.Table).Render
        - (*text/tabwriter.Writer).Flush
        # HTTP response writes - error is returned via other mechanisms
        - (net/http.ResponseWriter).Write
        # Cobra flag marking - panics on error anyway
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
    staticcheck:
      checks:
        - all
        - -QF1008
