# golangci-lint v2 configuration

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - cmd/thecloud
      - pkg/sdk
      - internal/handlers/ws
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/olekukonko/tablewriter.Table).Append
        - (*github.com/olekukonko/tablewriter.Table).Render
        - (net/http.ResponseWriter).Write
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - fmt.Fprintln
        - fmt.Fprintf
        - (*text/tabwriter.Writer).Flush
        - (*os.File).Close
        - (io.ReadCloser).Close
        - (io.Closer).Close
        - json.Unmarshal
        - os.Setenv
        - os.RemoveAll
    staticcheck:
      checks:
        - all
        - -QF1008
