version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - gosec
    - bodyclose
    - revive
    - errorlint
    - nilerr
    - gocritic
    - unparam
    - prealloc
    - nolintlint
    - misspell
    - unconvert
    - testifylint
    - thelper

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  errcheck:
    exclude-functions:
      - fmt.Fprintln
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println
      - (*github.com/olekukonko/tablewriter.Table).Append
      - (*github.com/olekukonko/tablewriter.Table).Render
      - (*text/tabwriter.Writer).Flush
      - (net/http.ResponseWriter).Write
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
  staticcheck:
    checks: ["all", "-QF1008"]
  gosec:
    excludes:
      - G101
      - G106

issues:
  exclude-rules:
    - path: cmd/thecloud
      linters:
        - errcheck
    - path: pkg/sdk
      linters: 
        - errcheck
    - path: internal/handlers/ws
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - gosec
