# golangci-lint v2 configuration
# See: https://golangci-lint.run/

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/olekukonko/tablewriter.Table).Append
        - (*github.com/olekukonko/tablewriter.Table).Render
        - (net/http.ResponseWriter).Write
        - (*github.com/spf13/cobra.Command).MarkFlagRequired

exclusions:
  paths:
    - cmd/thecloud
    - pkg/sdk
    - internal/handlers/ws
