version: 2

# golangci-lint configuration

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

issues:
  exclude-rules:
    - path: cmd/thecloud
      linters:
        - errcheck
    - path: pkg/sdk
      linters:
        - errcheck
    - path: internal/handlers/ws
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintln
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println
      - (*github.com/olekukonko/tablewriter.Table).Append
      - (*github.com/olekukonko/tablewriter.Table).Render
      - (*text/tabwriter.Writer).Flush
      - (net/http.ResponseWriter).Write
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
  staticcheck:
    checks: ["all", "-QF1008"]
