// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/storage/protocol/storage.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{0}
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Members       map[string]*MemberState `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterStatusResponse) GetMembers() map[string]*MemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

type GossipMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SenderId      string                  `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderAddr    string                  `protobuf:"bytes,2,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	Members       map[string]*MemberState `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key is node_id
	Timestamp     int64                   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GossipMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *GossipMessage) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

func (x *GossipMessage) GetMembers() map[string]*MemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GossipMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "alive", "suspect", "dead"
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Heartbeat     uint64                 `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{3}
}

func (x *MemberState) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MemberState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MemberState) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *MemberState) GetHeartbeat() uint64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GossipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StoreRequest_Metadata
	//	*StoreRequest_ChunkData
	Payload       isStoreRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{5}
}

func (x *StoreRequest) GetPayload() isStoreRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StoreRequest) GetMetadata() *StoreMetadata {
	if x != nil {
		if x, ok := x.Payload.(*StoreRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StoreRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*StoreRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isStoreRequest_Payload interface {
	isStoreRequest_Payload()
}

type StoreRequest_Metadata struct {
	Metadata *StoreMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type StoreRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*StoreRequest_Metadata) isStoreRequest_Payload() {}

func (*StoreRequest_ChunkData) isStoreRequest_Payload() {}

type StoreMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMetadata) Reset() {
	*x = StoreMetadata{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMetadata) ProtoMessage() {}

func (x *StoreMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMetadata.ProtoReflect.Descriptor instead.
func (*StoreMetadata) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{6}
}

func (x *StoreMetadata) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StoreMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StoreMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{7}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RetrieveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RetrieveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RetrieveResponse_Metadata
	//	*RetrieveResponse_ChunkData
	Payload       isRetrieveResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveResponse) GetPayload() isRetrieveResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RetrieveResponse) GetMetadata() *RetrieveMetadata {
	if x != nil {
		if x, ok := x.Payload.(*RetrieveResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *RetrieveResponse) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RetrieveResponse_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isRetrieveResponse_Payload interface {
	isRetrieveResponse_Payload()
}

type RetrieveResponse_Metadata struct {
	Metadata *RetrieveMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type RetrieveResponse_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*RetrieveResponse_Metadata) isRetrieveResponse_Payload() {}

func (*RetrieveResponse_ChunkData) isRetrieveResponse_Payload() {}

type RetrieveMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveMetadata) Reset() {
	*x = RetrieveMetadata{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveMetadata) ProtoMessage() {}

func (x *RetrieveMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveMetadata.ProtoReflect.Descriptor instead.
func (*RetrieveMetadata) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveMetadata) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RetrieveMetadata) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetrieveMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RetrieveMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AssembleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Parts         []string               `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssembleRequest) Reset() {
	*x = AssembleRequest{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssembleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssembleRequest) ProtoMessage() {}

func (x *AssembleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssembleRequest.ProtoReflect.Descriptor instead.
func (*AssembleRequest) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{13}
}

func (x *AssembleRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AssembleRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AssembleRequest) GetParts() []string {
	if x != nil {
		return x.Parts
	}
	return nil
}

type AssembleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssembleResponse) Reset() {
	*x = AssembleResponse{}
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssembleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssembleResponse) ProtoMessage() {}

func (x *AssembleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_protocol_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssembleResponse.ProtoReflect.Descriptor instead.
func (*AssembleResponse) Descriptor() ([]byte, []int) {
	return file_internal_storage_protocol_storage_proto_rawDescGZIP(), []int{14}
}

func (x *AssembleResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AssembleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_storage_protocol_storage_proto protoreflect.FileDescriptor

const file_internal_storage_protocol_storage_proto_rawDesc = "" +
	"\n" +
	"'internal/storage/protocol/storage.proto\x12\astorage\"\a\n" +
	"\x05Empty\"\xb0\x01\n" +
	"\x15ClusterStatusResponse\x12E\n" +
	"\amembers\x18\x01 \x03(\v2+.storage.ClusterStatusResponse.MembersEntryR\amembers\x1aP\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.storage.MemberStateR\x05value:\x028\x01\"\xfc\x01\n" +
	"\rGossipMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_addr\x18\x02 \x01(\tR\n" +
	"senderAddr\x12=\n" +
	"\amembers\x18\x03 \x03(\v2#.storage.GossipMessage.MembersEntryR\amembers\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1aP\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.storage.MemberStateR\x05value:\x028\x01\"t\n" +
	"\vMemberState\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\x04R\theartbeat\"*\n" +
	"\x0eGossipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"p\n" +
	"\fStoreRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.storage.StoreMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"v\n" +
	"\rStoreMetadata\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"?\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\";\n" +
	"\x0fRetrieveRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"w\n" +
	"\x10RetrieveResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.storage.RetrieveMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"{\n" +
	"\x10RetrieveMetadata\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"9\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"@\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x0fAssembleRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05parts\x18\x03 \x03(\tR\x05parts\"<\n" +
	"\x10AssembleResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x85\x03\n" +
	"\vStorageNode\x128\n" +
	"\x05Store\x12\x15.storage.StoreRequest\x1a\x16.storage.StoreResponse(\x01\x12A\n" +
	"\bRetrieve\x12\x18.storage.RetrieveRequest\x1a\x19.storage.RetrieveResponse0\x01\x129\n" +
	"\x06Delete\x12\x16.storage.DeleteRequest\x1a\x17.storage.DeleteResponse\x129\n" +
	"\x06Gossip\x12\x16.storage.GossipMessage\x1a\x17.storage.GossipResponse\x12B\n" +
	"\x10GetClusterStatus\x12\x0e.storage.Empty\x1a\x1e.storage.ClusterStatusResponse\x12?\n" +
	"\bAssemble\x12\x18.storage.AssembleRequest\x1a\x19.storage.AssembleResponseB\x1bZ\x19internal/storage/protocolb\x06proto3"

var (
	file_internal_storage_protocol_storage_proto_rawDescOnce sync.Once
	file_internal_storage_protocol_storage_proto_rawDescData []byte
)

func file_internal_storage_protocol_storage_proto_rawDescGZIP() []byte {
	file_internal_storage_protocol_storage_proto_rawDescOnce.Do(func() {
		file_internal_storage_protocol_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_storage_protocol_storage_proto_rawDesc), len(file_internal_storage_protocol_storage_proto_rawDesc)))
	})
	return file_internal_storage_protocol_storage_proto_rawDescData
}

var file_internal_storage_protocol_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_storage_protocol_storage_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: storage.Empty
	(*ClusterStatusResponse)(nil), // 1: storage.ClusterStatusResponse
	(*GossipMessage)(nil),         // 2: storage.GossipMessage
	(*MemberState)(nil),           // 3: storage.MemberState
	(*GossipResponse)(nil),        // 4: storage.GossipResponse
	(*StoreRequest)(nil),          // 5: storage.StoreRequest
	(*StoreMetadata)(nil),         // 6: storage.StoreMetadata
	(*StoreResponse)(nil),         // 7: storage.StoreResponse
	(*RetrieveRequest)(nil),       // 8: storage.RetrieveRequest
	(*RetrieveResponse)(nil),      // 9: storage.RetrieveResponse
	(*RetrieveMetadata)(nil),      // 10: storage.RetrieveMetadata
	(*DeleteRequest)(nil),         // 11: storage.DeleteRequest
	(*DeleteResponse)(nil),        // 12: storage.DeleteResponse
	(*AssembleRequest)(nil),       // 13: storage.AssembleRequest
	(*AssembleResponse)(nil),      // 14: storage.AssembleResponse
	nil,                           // 15: storage.ClusterStatusResponse.MembersEntry
	nil,                           // 16: storage.GossipMessage.MembersEntry
}
var file_internal_storage_protocol_storage_proto_depIdxs = []int32{
	15, // 0: storage.ClusterStatusResponse.members:type_name -> storage.ClusterStatusResponse.MembersEntry
	16, // 1: storage.GossipMessage.members:type_name -> storage.GossipMessage.MembersEntry
	6,  // 2: storage.StoreRequest.metadata:type_name -> storage.StoreMetadata
	10, // 3: storage.RetrieveResponse.metadata:type_name -> storage.RetrieveMetadata
	3,  // 4: storage.ClusterStatusResponse.MembersEntry.value:type_name -> storage.MemberState
	3,  // 5: storage.GossipMessage.MembersEntry.value:type_name -> storage.MemberState
	5,  // 6: storage.StorageNode.Store:input_type -> storage.StoreRequest
	8,  // 7: storage.StorageNode.Retrieve:input_type -> storage.RetrieveRequest
	11, // 8: storage.StorageNode.Delete:input_type -> storage.DeleteRequest
	2,  // 9: storage.StorageNode.Gossip:input_type -> storage.GossipMessage
	0,  // 10: storage.StorageNode.GetClusterStatus:input_type -> storage.Empty
	13, // 11: storage.StorageNode.Assemble:input_type -> storage.AssembleRequest
	7,  // 12: storage.StorageNode.Store:output_type -> storage.StoreResponse
	9,  // 13: storage.StorageNode.Retrieve:output_type -> storage.RetrieveResponse
	12, // 14: storage.StorageNode.Delete:output_type -> storage.DeleteResponse
	4,  // 15: storage.StorageNode.Gossip:output_type -> storage.GossipResponse
	1,  // 16: storage.StorageNode.GetClusterStatus:output_type -> storage.ClusterStatusResponse
	14, // 17: storage.StorageNode.Assemble:output_type -> storage.AssembleResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_storage_protocol_storage_proto_init() }
func file_internal_storage_protocol_storage_proto_init() {
	if File_internal_storage_protocol_storage_proto != nil {
		return
	}
	file_internal_storage_protocol_storage_proto_msgTypes[5].OneofWrappers = []any{
		(*StoreRequest_Metadata)(nil),
		(*StoreRequest_ChunkData)(nil),
	}
	file_internal_storage_protocol_storage_proto_msgTypes[9].OneofWrappers = []any{
		(*RetrieveResponse_Metadata)(nil),
		(*RetrieveResponse_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_storage_protocol_storage_proto_rawDesc), len(file_internal_storage_protocol_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_storage_protocol_storage_proto_goTypes,
		DependencyIndexes: file_internal_storage_protocol_storage_proto_depIdxs,
		MessageInfos:      file_internal_storage_protocol_storage_proto_msgTypes,
	}.Build()
	File_internal_storage_protocol_storage_proto = out.File
	file_internal_storage_protocol_storage_proto_goTypes = nil
	file_internal_storage_protocol_storage_proto_depIdxs = nil
}
