-- +goose Up

CREATE TABLE IF NOT EXISTS vpcs (
    id UUID PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    network_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE instances ADD COLUMN vpc_id UUID REFERENCES vpcs(id);
