DROP INDEX IF EXISTS idx_images_tenant;
DROP INDEX IF EXISTS idx_stacks_tenant;
DROP INDEX IF EXISTS idx_deployments_tenant;
DROP INDEX IF EXISTS idx_gateway_routes_tenant;
DROP INDEX IF EXISTS idx_cron_jobs_tenant;
DROP INDEX IF EXISTS idx_subscriptions_tenant;
DROP INDEX IF EXISTS idx_topics_tenant;
DROP INDEX IF EXISTS idx_queues_tenant;
DROP INDEX IF EXISTS idx_caches_tenant;
DROP INDEX IF EXISTS idx_functions_tenant;
DROP INDEX IF EXISTS idx_secrets_tenant;
DROP INDEX IF EXISTS idx_snapshots_tenant;
DROP INDEX IF EXISTS idx_subnets_tenant;
DROP INDEX IF EXISTS idx_security_groups_tenant;
DROP INDEX IF EXISTS idx_floating_ips_tenant;
DROP INDEX IF EXISTS idx_clusters_tenant;
DROP INDEX IF EXISTS idx_buckets_tenant;
DROP INDEX IF EXISTS idx_scaling_groups_tenant;
DROP INDEX IF EXISTS idx_load_balancers_tenant;
DROP INDEX IF EXISTS idx_volumes_tenant;
DROP INDEX IF EXISTS idx_vpcs_tenant;
DROP INDEX IF EXISTS idx_instances_tenant;

ALTER TABLE images DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE stacks DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE deployments DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE gateway_routes DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE cron_jobs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE topics DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE queues DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE caches DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE functions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE secrets DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE snapshots DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE subnets DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE security_groups DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE IF EXISTS floating_ips DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE clusters DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE buckets DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE scaling_groups DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE load_balancers DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE volumes DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE vpcs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE instances DROP COLUMN IF EXISTS tenant_id;
