ALTER TABLE instances 
ADD COLUMN IF NOT EXISTS volume_binds TEXT[],
ADD COLUMN IF NOT EXISTS env TEXT[],
ADD COLUMN IF NOT EXISTS cmd TEXT[],
ADD COLUMN IF NOT EXISTS cpu_limit BIGINT,
ADD COLUMN IF NOT EXISTS memory_limit BIGINT,
ADD COLUMN IF NOT EXISTS disk_limit BIGINT;
