-- +goose Up
ALTER TABLE databases ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'PRIMARY' NOT NULL;
ALTER TABLE databases ADD COLUMN IF NOT EXISTS primary_id UUID REFERENCES databases(id) ON DELETE CASCADE;

-- +goose Down
ALTER TABLE databases DROP COLUMN IF EXISTS primary_id;
ALTER TABLE databases DROP COLUMN IF EXISTS role;
